repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: master
      hooks:
        - id: check-merge-conflict
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
          - id: black
            language_version: python3.6
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v5.12.0
      hooks:
          - id: eslint
            additional_dependencies:
            - eslint@5.6.0
            - prettier@1.15.3
            - eslint-plugin-react@7.11.1
            - eslint-config-react-app@3.0.5
            - eslint-plugin-prettier@3.0.0
            - eslint-config-prettier@3.3.0
            - eslint-plugin-import@2.14.0
            - eslint-plugin-flowtype@2.50.1
            - eslint-plugin-jsx-a11y@6.1.2
            - babel-eslint@9.0.0